version: "3"
services: 
  zookeeper:  
    image: confluentinc/cp-zookeeper:${CONFLUENT_PLATFORM_VERSION:-3.0.0}
    ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
    networks:
      - kxploreNet
    environment:
    - ZOOKEEPER_SERVER_ID=1
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
    - ZOOKEEPER_INIT_LIMIT=5
    - ZOOKEEPER_SYNC_LIMIT=2
    - ZOOKEEPER_SERVERS=zookeeper:2888:3888
  kafka:
    image: confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-3.0.0}
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
    - zookeeper
    ports:
    - "9091:9091"
    networks:
      - kxploreNet
    environment:
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9091
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=1
    - BOOTSTRAP_SERVERS=kafka:9091
    - ZOOKEEPER=zookeeper:2181
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
       - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: kxplore
      MYSQL_DATABASE: kxplore
      MYSQL_USER: kxplore
      MYSQL_PASSWORD: kxplore
    networks:
      - kxploreNet
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - kxploreNet
    volumes:
       - $PWD/redis:/data
networks:
  kxploreNet: